kind: pipeline
name: default

steps:
- name: npm
  image: plugins/npm
  when:
    event: [ tag ]
  settings:
    username:
      from_secret: NPM_USERNAME
    password:
      from_secret: NPM_PASSWORD
    token:
      from_secret: NPM_ACCESSTOKEN
    email:
      from_secret: NPM_EMAIL
